### PR TITLE
Add ODE content and configure sphinx extension for additional special blocks.

### PR DESCRIPTION
**Pull request by brysonwu**

### CODE REVIEW

**Comment by brysonwu** [comment]
Jupyter Book raises a lot of duplicate label warnings when building, but this hasn't caused any real issues as far as I can tell.

From the warning messages, my understanding is that Jupyter Book expects the labels for all files within the same folder to be unique. However, I didn't know this beforehand and so only programmed the parsing script to assign unique labels at the file level, instead of at the folder level.

I left these labels as is because they are necessary for equation numbering to render properly. Moreover, only equations that are not referenced in the text are affected. I can fix the duplicate labels later if needed.

**Comment by brysonwu** [comment]
Also, the bad markdown formatting is an artifact of the parsing script. It doesn't affect rendering but I can also fix this later if needed/there is time.

**Review by patrickwalls — CHANGES_REQUESTED** [review]
This is looking good. I am going to have to manually edit a lot of the content to simplify the presentation and improve the section numbering.

There are a couple of things that I hope the parser can do:

1. Generate unique references using, for example, names of the form: (ref-foldername-filename-01).
2. Do a search an replace to remove the macros at the top of each .md file. For example, there is no need for `\la` to replace `\lambda` and `\rme` should just be `e`. Try to remove as many as possible but we can remove them manually when editing each page.

**Comment by brysonwu** [comment]
I've implemented a new labeling script to generate unique references for all equations and examples that don't already have a unique label. I included unique references for examples too since those were raising warnings as well. I have also added a step to the original parsing script to replace all simple macros--i.e. ones that do not accept arguments.

FYI, I am keeping the labeling script separate from the original parsing script to save time: I only decide on a concise filename for the markdown files after reading through the content/fixing edge cases. I can still implement this functionality into the original parsing script in the future if time allows or if it's preferred--trying to get through parsing as soon as I can.

**Review by patrickwalls — APPROVED** [review]

**Pull request merged**
